### ISSUE TITLE
Set up Next Js boilerplate

### ISSUE THREAD

**Issue by kelvinsekx** [Ibadan-Techies/badtechies#1]
Setup a simple Nestjs boilerplate. This link https://nextjs.org/docs/getting-started is a good place to start.

**Comment by WojuadeAA** [comment]
the project should typescript enabled?

**Comment by kelvinsekx** [comment]
Yes it should be strictly typescript.

**Comment by WojuadeAA** [comment]
Noted

**Comment by WojuadeAA** [comment]
.take

**Comment by kelvinsekx** [comment]
Kindly note that every issue changes must be on a branch. There is a "create a branch" link on the Development section in every issue menu. You can decide to use it or manually create a branch.

![Screenshot_20230204-232947](https://user-images.githubusercontent.com/51183064/216792174-b7183aed-9852-41de-a21a-5d2195e43d3e.jpg)

**Comment by kelvinsekx** [comment]
closed by merged https://github.com/Ibadan-Techies/badtechies/pull/16
