### ISSUE TITLE
feat: add navbar

### ISSUE THREAD

**Issue by kelvinsekx** [Ibadan-Techies/badtechies#20]
screenshot
![header nav](https://user-images.githubusercontent.com/51183064/229475552-9b5f7a63-c9b2-40ee-b29a-c1ac48f0abcc.png)

Link
https://www.figma.com/file/e6sfiMNbpYefqIeC6BDHYT/Ibadan-Techies-Website?node-id=49-233&t=YkJ3aRxLcp7v8RD9-0

| Dependencies   |     |   |
|--------------|-----------|----------|
| Test | Not required      |    |
| Logo component     | #21 | available |
| Link component     | #23  | available |
| Button component     | #24  | available |

**Comment by Demoivre02** [comment]
.take

**Comment by kelvinsekx** [comment]
.take
