### ISSUE TITLE
feat: Button component

### ISSUE THREAD

**Issue by kelvinsekx** [Ibadan-Techies/badtechies#24]
Button should meet the following conditions:
- Button Like Links
- Button (without links)
- Button with an icon
- Button with border or not, background or not, block background or not

Link
https://www.figma.com/file/e6sfiMNbpYefqIeC6BDHYT/Ibadan-Techies-Website?node-id=49-233&t=lHpK5ejdSyLDeMxe-0

See images for samples
![Screenshotbtn5](https://user-images.githubusercontent.com/51183064/229485631-96da719b-ffde-4dac-8588-6182e5eae107.png)
![ScreenshotButton3](https://user-images.githubusercontent.com/51183064/229485714-00c2a667-bd29-4eb2-a9e4-ce7375b0e726.png)
![ScreenshotButtons2](https://user-images.githubusercontent.com/51183064/229485715-82098bbb-c316-408d-91da-d63b7876b2af.png)
![ScreenshotButtons](https://user-images.githubusercontent.com/51183064/229485719-49b5a884-3c8a-4e4f-8e13-36840184eddf.png)
![Screenshotbutton4](https://user-images.githubusercontent.com/51183064/229485721-90479737-4bc6-4e6a-b522-79e3770887f2.png)

**Comment by kelvinsekx** [comment]
.take

**Comment by kelvinsekx** [comment]
I have one more addition to make 😁😂
I'm sorry

**Comment by WojuadeAA** [comment]
Omooo
Okay
