### ISSUE TITLE
feat: Homepage Section 1

### ISSUE THREAD

**Issue by kelvinsekx** [Ibadan-Techies/badtechies#29]
link
https://www.figma.com/file/e6sfiMNbpYefqIeC6BDHYT/Ibadan-Techies-Website?node-id=49-233&t=yg1zLIex3oxD4ABG-0

screenshot
![Screenshot Header Section 1](https://user-images.githubusercontent.com/51183064/229759335-d3708f01-c7d7-42bb-9834-9cfad1d18b69.png)

|   Dependencies  |    |   |
|----|----|----|
|  Navbar   |    https://github.com/Ibadan-Techies/badtechies/issues/20  | available |
| Link Component | https://github.com/Ibadan-Techies/badtechies/issues/23 | available |
| Button Component | https://github.com/Ibadan-Techies/badtechies/issues/24| Available |

**Comment by Demoivre02** [comment]
.take

**Comment by kelvinsekx** [comment]
Did you see the dependencies for this component before taking this issue?
You can't build this component if all it's dependencies is not market "available".

**Comment by kelvinsekx** [comment]
You should take one of it's dependencies first before building a large component like this one.

**Comment by Demoivre02** [comment]
I copy will start with #20

**Comment by kelvinsekx** [comment]
You've not assigned #20 to yourself. Can you please do that?

**Comment by Demoivre02** [comment]
roger that
Assigned #20 to myself.
I repeat, assigned #20 to myself.

out

**Comment by kelvinsekx** [comment]
The two arrows on this component are available are React component https://github.com/Ibadan-Techies/badtechies/blob/main/src/assets/svg.ts

**Comment by kelvinsekx** [comment]
.take
