### ISSUE TITLE
feat: SubscribeNewsletter Component

### ISSUE THREAD

**Issue by kelvinsekx** [Ibadan-Techies/badtechies#41]
## link
https://www.figma.com/file/e6sfiMNbpYefqIeC6BDHYT/Ibadan-Techies-Website?node-id=52-514&t=t79dVIwAZvQjEA9E-0

## screenshot
![ScreenshotSubscribeNewsletter](https://user-images.githubusercontent.com/51183064/230557487-5dab9035-0655-43b0-90e6-aa22aad1323b.png)

## Further info
- SquiggleLeft and SquiggleRight should be imported as SVGs.
- All SVGs are downloaded into the "/src/assets" folder and exported as default from the "src/assets/svg.ts" file.

|  Dependencies  |     |   |
|-------|--------|--------|
|  Button  |  #34 | Available|

**\##footer**
The input field would have been a standalone custom component but an input component could get messy for us at this stage.

**Comment by josephden16** [comment]
.take

**Comment by kelvinsekx** [comment]
Hey @josephden16 ,
Give me a moment to force merge the PRs. Then you can make a rebase before adding your component.
I will let you know when I am done (in less than a minute)

**Comment by josephden16** [comment]
Alright, no problem.

**Comment by kelvinsekx** [comment]
I am done.
run `git pull --rebase origin main` on your branch

**Comment by kelvinsekx** [comment]
Closed by https://github.com/Ibadan-Techies/badtechies/pull/59
