### ISSUE TITLE
feat: SEO configuration

### ISSUE THREAD

**Issue by josephden16** [Ibadan-Techies/badtechies#61]
- Create a component for adding page-specific SEO metadata with the `next-seo` package.
- Add the `next-sitemap`  package for generating sitemaps.

**Comment by josephden16** [comment]
.take

**Comment by kelvinsekx** [comment]
What is the progress on this issue?

**Comment by josephden16** [comment]
Sorry for the late response. One of the features for this issue will require an active deployment for it to be properly tested.

**Comment by kelvinsekx** [comment]
closed by #88
