### ISSUE TITLE
Update Website Title to "Ibadan Techies Club

### ISSUE THREAD

**Issue by WojuadeAA** [Ibadan-Techies/badtechies#80]
Currently, the title of our website reads "Create React App", which is not an accurate representation of the content and purpose of our website. As a community of tech enthusiasts in Ibadan, it is important that our website accurately reflects our identity and mission.

I propose that we update the website title to "Ibadan Techies Club" to better represent our community and its values. This will not only make it easier for users to understand what our website is about, but it will also enhance our brand identity and make us more recognizable within the local tech community.

**Task List:**

- Update the website title to "Ibadan Techies Club" on the homepage.
- Update the website title in the website's metadata to ensure that it is correctly displayed on search engine results.
- Test the website to ensure that the new title is properly reflected throughout the website.

**Comment by kelvinsekx** [comment]
Closed by #88
